{"author":{"id":"4d85ccdde3ad47c902de21b580354b67ed0cb07caa04e32d04ea93112f7f027e"},"ops":[{"type":5,"timestamp":1743438828,"nonce":"The84XeMXFt3UTOvASRghMkCcEw=","metadata":{"github-id":"LE_lADOCGKeh86kj4xbzwAAAAP44WMI"},"added":["kind/feature"],"removed":[]},{"type":5,"timestamp":1743438828,"nonce":"FcWJAZHsPAtaPNNuZbvFIL9XN+U=","metadata":{"github-id":"LE_lADOCGKeh86kj4xbzwAAAAP44WMO"},"added":["lifecycle/frozen"],"removed":[]},{"type":5,"timestamp":1743438829,"nonce":"0gppepOj8ve+E7s5KMOvCvQ+Oc0=","metadata":{"github-id":"LE_lADOCGKeh86kj4xbzwAAAAP44WMX"},"added":["priority/backlog"],"removed":[]},{"type":5,"timestamp":1743438829,"nonce":"U67czzKr/XTR63jrFzesm0E672E=","metadata":{"github-id":"LE_lADOCGKeh86kj4xbzwAAAAP44WMh"},"added":["area/git"],"removed":[]},{"type":5,"timestamp":1743439113,"nonce":"yE6cjc3g4OwaAp0Wu3zKpIBAGho=","metadata":{"github-id":"UNLE_lADOCGKeh86kj4xbzwAAAAP44lnz"},"added":[],"removed":["lifecycle/stale"]},{"type":3,"timestamp":1743468122,"nonce":"vauyV091KNCHOCvutBz6PKoqqFE=","metadata":{"github-id":"IC_kwDOCGKeh86k-E3k","github-url":"https://github.com/git-bug/git-bug/issues/1316#issuecomment-2767736292"},"message":"@s1ls thanks for opening this issue. i think this makes sense to me, but just to confirm, you have a repository set up like this?\n\n```\nâžœ git remote -v\norigin  https://github.com/git-bug/git-bug.git (fetch)\norigin  ssh://git@github.com/git-bug/git-bug.git (push)\n```\n\nwhat command(s) are you running that cause the authorization failed error? does this happen natively, or over a bridge?","files":null}]}