{"author":{"id":"a44d49272efd2dd9fe393bc4e24726ca386fde0ba32ff78231f60ea8c81c1e22"},"ops":[{"type":3,"timestamp":1746735491,"nonce":"uGZAp2hibXb4bSuM4PalKxAQXE0=","metadata":{"github-id":"IC_kwDOCGKeh86qt-B5","github-url":"https://github.com/git-bug/git-bug/issues/1139#issuecomment-2864177273"},"message":"Hey @sudoforge ,\nYes I confirm those 4 points.\n\nI am not on the multiple identity computer right now, but I tried running v0.8.1 and got auth issues as well. Maybe they are unrelated though:\n\n```\ncd $(mktemp -d) \u0026\u0026 git init .\ngit remote add origin git@github.com:git-bug/git-bug.git\ngit ls-remote origin refs/tags/\\* | sed -e 's/refs\\/tags\\///'\ngit fetch --no-tags --depth 1 origin +refs/tags/v0.8.1:refs/tags/v0.8.1\ngit checkout v0.8.1\nmake build\n\ncd /tmp\ngit clone git@github.com:MartyLake/test_git_bug.git\necho \"# test_git_bug\" \u003e\u003e README.md\ngit init\ngit add README.md\ngit commit -m \"first commit\"\ngit branch -M master\ngit remote add origin git@github.com:MartyLake/test_git_bug.git\ngit push -u origin master\n/tmp/tmp.45SGRM4ps5/git-bug pull\n```\nI get this error when trying to git bug pull:\n```\nFetching remote ...\nError: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain\n```\nNot sure if related though.","files":null}]}