{"author":{"id":"59a2f359586e946d8ec4166b24a94b0d829d6a0141f6b9491303c351493e2f5c"},"ops":[{"type":1,"timestamp":1622456239,"nonce":"ZRBH5Pej297WsmX898eXBU6mu00=","metadata":{"github-id":"MDU6SXNzdWU5MDczMzE2OTI=","github-url":"https://github.com/git-bug/git-bug/issues/686","origin":"github"},"title":"bridge pull gives: rofi.current/build$ git bug bridge pull panic: runtime error: index out of range [0] with length 0","message":"After an initial pull (that worked) I made an online change (closed bug) and did another bridge pull, this returned the following trace:\n\n```\npanic: runtime error: index out of range [0] with length 0\n\ngoroutine 42 [running]:\ngithub.com/MichaelMure/git-bug/bridge/github.(*iterator).NextTimelineItem(0xc000246140, 0xc000130d00)\n\t/home/michael/dev/git-bug/bridge/github/iterator.go:252 +0x405\ngithub.com/MichaelMure/git-bug/bridge/github.(*githubImporter).ImportAll.func1(0xc0003cc1e0, 0xc000130d80, 0xc00011d140)\n\t/home/michael/dev/git-bug/bridge/github/import.go:75 +0x8a\ncreated by github.com/MichaelMure/git-bug/bridge/github.(*githubImporter).ImportAll\n\t/home/michael/dev/git-bug/bridge/github/import.go:60 +0x1bf\n```\n\nVersion:\n```\n$git bug --version\ngit-bug version v0.7.2\n```\n\nPlease let me know if you need more information.","files":null}]}