{"author":{"id":"d4653411f4a58b3edc7f3d9d4e10aa8ba6fc9bdc300c319b4db20e051c761228"},"ops":[{"type":1,"timestamp":1586614788,"nonce":"ZAkhOU6qymbB8U2CdgqBrjGDTnk=","metadata":{"github-id":"MDU6SXNzdWU1OTgyNzU0MTI=","github-url":"https://github.com/git-bug/git-bug/issues/369","origin":"github"},"title":"Gitlab bridge misbehaving with identities","message":"What I've done:\n1. created a user and configured a bridge, specifying my Gitlab username as login and a valid token\n2. created an issue\n3. successfully pushed\n4. edited the issue on gitlab (added labels)\n5. pulled. The issue was duplicated, and the identity appeared different (had the full name)\n6. deleted and re-created the bridge, this time with my email as login and the same token as before\n7. removed old auth with `git bug auth rm \u003cold_auth_id\u003e`\n\nAt this point, this is the situation:\n```bash\n$\u003e git bug bridge auth\nError: unknown credential type \"\"\n$\u003e git bug bridge pull\nError: unknown credential type \"\"\n$\u003e git bug bridge auth add-token \u003cmy_token\u003e -t gitlab -l \u003cmy_email\u003e\nError: this user is already tagged with a different gitlab login\n```\n\nWhat do?","files":null}]}