{"author":{"id":"dad7de907207eabd1b9f613e275314a036b2d81e5397d5e8de5d03b586136780"},"ops":[{"type":1,"timestamp":1660561895,"nonce":"4wuk2CFKeYmdIGqxRHd9Wz0eXo8=","metadata":{"github-id":"I_kwDOCGKeh85PzTKp","github-url":"https://github.com/git-bug/git-bug/issues/845","origin":"github"},"title":"`git bug pull` fails with panic: DFS failed","message":"First of all thanks for your excellent software.\n\nwhen doing a `git bug pull` on an already established repository, but which has not been checked out on this machine before, with the latest master (cd528724), I get the following error:\n\n```\n\nFetching remote ...\nalready up-to-datealready up-to-date\nMerging data ...\npanic: DFS failed\n\ngoroutine 77 [running]:\ngithub.com/MichaelMure/git-bug/entity/dag.read({{0x1185c0c, 0x3}, {0x11863aa, 0x4}, 0x12391d8, 0x4}, {0x136fba0, 0xc000400420}, {0x1356e40, 0xc0005302d0}, ...)\n        /home/danw/Software/git-bug/entity/dag/entity.go:164 +0xf90\ngithub.com/MichaelMure/git-bug/entity/dag.merge({{0x1185c0c, 0x3}, {0x11863aa, 0x4}, 0x12391d8, 0x4}, {0x136fba0?, 0xc000400420}, {0x1356e40, 0xc0005302d0}, ...)\n        /home/danw/Software/git-bug/entity/dag/entity_actions.go:101 +0x185\ngithub.com/MichaelMure/git-bug/entity/dag.MergeAll.func1()\n        /home/danw/Software/git-bug/entity/dag/entity_actions.go:85 +0x2cf\ncreated by github.com/MichaelMure/git-bug/entity/dag.MergeAll\n        /home/danw/Software/git-bug/entity/dag/entity_actions.go:74 +0x1a5\n\n```\n\nthis does seem to be an issue with this specific repo, and it's not a problem for me to reset it and re-import all the issues from gitlab. But I couldn't find out how to safely do that.","files":null}]}