{"author":{"id":"2b0986c30bd65cfe661c673862fd08c9ede1d16106bec7c7b1464ae9649c3b5f"},"ops":[{"type":1,"timestamp":1603789042,"nonce":"ON0s4zQJFFC2n5jKX59f/ToldoU=","metadata":{"github-id":"MDU6SXNzdWU3MzAyNDk2NTk=","github-url":"https://github.com/git-bug/git-bug/issues/477","origin":"github"},"title":"[gitlab] Adding bridge fails","message":"I recently found this project and found it to be a perfect candidate to backup projects from a gitlab instance i will soon lose access to.\nI've had unrelated problems with the latest release, so i chose to use the current git version.\nBut i found it hard to add the bridge authentification to the config in this version (In the release version this did work).\n\n\nRelease:\n```\n➜  project git:(master) ../../git-bug_linux_amd64 bridge configure -t gitlab -u gitlab.example.com/path/project -b https://gitlab.example.com/ -n default\nBuilding identity cache... Done.\nBuilding bug cache... Done.\nGitlab login: ^C\n\n➜  project git:(master) ../../git-bug_linux_amd64 bridge configure -t gitlab -u gitlab.example.com/path/project -b https://gitlab.example.com/ -n default --token *****************\nIdentity d48fb1a created, set as current\nSuccessfully configured bridge: default\n```\n\nGit version:\n```\n➜  project git:(master) git bug bridge configure -t gitlab -u https://gitlab.example.com/path/project -b https://gitlab.example.com/ --token ************** -n default\nA lock file is present but the corresponding process is not, removing it.\nIdentity 97fb07e created, set as current\nSuccessfully configured bridge: default\n➜  project git:(master) git bug bridge pull\nA lock file is present but the corresponding process is not, removing it.\nError: loading credential: no credential salt found\n➜  project git:(master) git bug bridge auth\nError: loading credential: no credential salt found\n```\n\nI tried to reconstruct what went wrong, and i suspect that the call to `auth.List` in `config.promptTokenOptions` \"throws\" this error.\nI managed to get the git version of git-bug working again by commenting out `return nil, err` and replacing it with continue at line 162,168 in auth.credentials.\nBut as this is just a very messy workaround - do you have any idea what causes this? Or should i try to find a real fix?\n\nDisclaimer: I'm new to this project and also have *no* experience with golang.","files":null}]}