{"author":{"id":"46cd44f31415945f2a75664577fe8217fa7d6b8c64998ffd2534046ceb867b4d"},"ops":[{"type":3,"timestamp":1747145719,"nonce":"8cGf8rtMUlW+ywwN8hEcVHM/tBg=","metadata":{"github-id":"IC_kwDOCGKeh86rdw6S","github-url":"https://github.com/git-bug/git-bug/issues/1416#issuecomment-2876706450"},"message":"Hello. I read your vision of the future and the corresponding discussion, but I really don't have much technical knowledge on many of the topics you discussed, I leaved a comment but I don't address much issues there. Maybe I could reread that in the future and give a much more informed opinion :)\n\n---\n\n```\nwhat does the URL for your origin remote look like? (you can redact the user and repo names if you'd prefer)\n```\n\nThis is my repo URL: https://github.com/JoacoG/suite-cupones.\n\nIt is private repo.\n\n```\nwhat happens if you run git bug push on the command line?\n```\n\nIt does not work. It gives me the same error as in the TUI `Error: authentication required: Repository not found.`\n\nI can push and pull using `git bug bridge push origin` and `git bug bridge pull origin` respectively.","files":null}]}